add_newline = false

[localip]
disabled = true

[character]
success_symbol = "[â€º](bold green)"
error_symbol = "[â€º](bold red)"

[username]
disabled = true

[directory]
read_only = "î‚¢"

[golang]
symbol = "go "

[nodejs]
symbol = "js "

[nix_shell]
symbol = "ğŸ¸ "

[python]
symbol = "py "

[ruby]
symbol = "rb "

[rust]
symbol = "rs "

[jobs]
symbol = "âŠ•"

[git_status]
# Too slow at the moment... Reconsider in the future
disabled = true

[hostname]
ssh_symbol = "â‰ "

[lua]
symbol = "â¾ "
